# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "Precise32"

  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.define "web" do |web|
    web.vm.network :forwarded_port, guest: 80, host: 8080
    web.vm.network "private_network", ip: "192.168.50.1"
    web.vm.hostname = "web.server.vm"
  end

  config.vm.define "database" do |database|
    database.vm.network "private_network", ip: "192.168.50.2"
    database.vm.hostname = "database.server.vm"
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "default.pp"
  end  
end
